---
default:
    - debug: true
      open: http://localhost:8000/public
      extra: -use-network=false -static-link-runtime-shared-libraries
    
library-path:
    - source/swc

source-path:
    - source/libs
    - source/classes
    
applications:
    - class: source/classes/TmTest.as
      output: public/tmTest.swf
      
    - class: source/classes/tmTest/views/Main.as
      output: public/main.swf
      
    - class: source/classes/tmTest/views/SectionOne.as
      output: public/sectionOne.swf   
    
    - class: source/classes/tmTest/views/SectionTwo.as
      output: public/sectionTwo.swf

# asdoc:
#     - title: "My ActionScript project"
#       footer: "My ActionScript project footer"
#       output: docs/
#       exclude-dirs: 
#         - source/classes/com/greensock/
#         - source/classes/br/com/stimuli/
